blueboat_teleop:
  ros__parameters:
    joy_topic: /joy
    cmd_vel_topic: /cmd_vel

    publish_rate: 20.0
    command_timeout: 0.5

    axis_linear_x: 1
    axis_angular_z: 3

    scale_linear_x: 0.5
    scale_angular_z: 0.5
    turbo_scale_linear_x: 0.5
    turbo_scale_angular_z: 0.5

    enable_button: 5
    turbo_button: -1
    require_enable_button: false

    mode_modifier_button: 5
    alternate_mode_modifier_button: -1
    body_force_button: 4
    body_velocity_button: 2
    stop_controllers_button: -1

    controller_manager_name: /controller_manager
    body_force_controller_name: body_force_controller
    body_velocity_controller_name: body_velocity_controller
    thruster_test_controller_name: thruster_test_controller

    axis_deadzone: 0.1
    invert_linear_x: false
    invert_angular_z: false
