controller_manager:
  ros__parameters:
    update_rate: 50

    hardware_components_initial_state:
      inactive:
        - ThrustersSystem
        - SensorsSystem

    thruster_test_controller:
      type: forward_command_controller/ForwardCommandController

    body_force_controller:
      type: catamaran_controllers/BodyForceController
    
    body_velocity_controller:
      type: catamaran_controllers/BodyVelocityController

    body_position_controller:
      type: catamaran_controllers/BodyPositionController

    imu_broadcaster:
      type: imu_sensor_broadcaster/IMUSensorBroadcaster

    # magnetometer_broadcaster:
    #   type: sura_sensors/MagnetometerBroadcaster

thruster_test_controller:
  ros__parameters:
    joints:
      - blueboat/left_thruster_joint
      - blueboat/right_thruster_joint
    interface_name: effort

body_force_controller:
  ros__parameters:
    input_topic: /body_force/command
    base_link: blueboat/base_link
    thruster_joints:
      - blueboat/left_thruster_joint
      - blueboat/right_thruster_joint

body_velocity_controller:
  ros__parameters:
    cmd_vel_topic: /cmd_vel
    navigator_topic: /navigator_msg
    body_force_controller_name: body_force_controller

    kp_u: 250.0
    ki_u: 22.0
    kd_u: 48.0
    integral_limit_u: 14.0

    kp_r: 210.0
    ki_r: 22.0
    kd_r: 48.0
    integral_limit_r: 10.0


body_position_controller:
  ros__parameters:
    navigator_topic: /navigator_msg
    setpoint_topic: /body_position/setpoint
    body_velocity_controller_name: body_velocity_controller

    kp_position: 0.20
    kp_yaw: 0.35
    max_linear_speed: 0.2
    max_angular_speed: 0.12
    position_hold_radius: 0.25
    yaw_tolerance: 0.12
    slow_down_radius: 1.50
    heading_error_stop: 1.20
    reverse_distance_threshold: 1.00
    max_reverse_speed: 0.04
    yaw_command_sign: -1.0

navigator_bridge:
  ros__parameters:
    linear_lpf_alpha: 0.50

thrusters_system:
  ros__parameters:
    thruster_lpf_alpha: 0.20

imu_broadcaster:
  ros__parameters:
    sensor_name: imu_sensor
    frame_id: blueboat/imu_link

# magnetometer_broadcaster:
#   ros__parameters:
#     sensor_name: magnetometer_sensor
#     frame_id: blueboat/imu_link
#     topic_name: /magnetometer_broadcaster/mag
